name: Build Android APK

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch: # Cho phép kích hoạt build thủ công từ giao diện Web của GitHub

jobs:
  build:
    name: Build Flutter APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Generate files
        run: |
          dart run build_runner build --delete-conflicting-outputs
          dart pub global activate flutter_gen
          fluttergen

      - name: Build APK
        run: |
          flutter build apk \
            --release \
            --no-tree-shake-icons \
            --obfuscate \
            --split-debug-info=./symbols \
            --android-skip-build-dependency-validation

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: xlist-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
